"""describe changes.

Revision ID: c7cfe4cef7bf
Revises: 37ec1c213b9b
Create Date: 2025-01-30 21:19:44.075806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7cfe4cef7bf'
down_revision = '37ec1c213b9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
